sudo_enabled: required
language: java
jdk:
  - oraclejdk9
# - openjdk9 # TODO openjdk9 is not available on Ubuntu 15.04, we have to pull 16.04 before build

install: mvn dependency:go-offline -B -V -P $CONTAINER

cache:
    directories:
        - $HOME/.m2

addons:
  sonarcloud:
    organization: "ok"

jobs:
  include:
    - jdk: oraclejdk9
      env:
        - CONTAINER=wildfly
      script: mvn clean test sonar:sonar -B -P $CONTAINER
    #- jdk: oraclejdk9 disable until payara supports Java 9
    #  env:
    #    - CONTAINER=payara
    #  script: mvn clean test -B -P $CONTAINER
