language: java
jdk:
  - oraclejdk9
# - openjdk9 # TODO openjdk9 is not available on Ubuntu 15.04, we have to pull 16.04 before build

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P $CONTAINER

cache:
    directories:
        - $HOME/.m2

addons:
  sonarcloud:
    organization: "ok"

# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=

jobs:
  include:
    - jdk: oraclejdk9
      env:
        - CONTAINER=wildfly
      script: mvn test -B -P $CONTAINER sonar:sonar
    #- jdk: oraclejdk9 disable until payara supports Java 9
    #  env:
    #    - CONTAINER=payara
    #  script: mvn test -B -P $CONTAINER
